language: d
sudo: false

matrix:
    include:
        - d: dmd-2.080.1

script:
  - dub test --build=unittest-cov --compiler=${DC}
  - dub run -c example

after_success:
 - bash <(curl -s https://codecov.io/bash)
