language: d
sudo: false

matrix:
    include:
        - d: dmd-2.084.0
        - d: dmd-2.083.1
        - d: dmd-2.082.1
        - d: ldc-1.13.0
        - d: ldc-1.12.0
        - d: ldc-1.11.0

script:
  - dub test --build=unittest-cov --compiler=${DC}
  - dub run -c example

after_success:
 - bash <(curl -s https://codecov.io/bash)
