language: d
sudo: false

matrix:
    include:
        - d: dmd-2.082.0
        - d: dmd-2.081.2
        - d: dmd-2.080.1
        - d: ldc-1.11.0

script:
  - dub test --build=unittest-cov --compiler=${DC}
  - dub run -c example

after_success:
 - bash <(curl -s https://codecov.io/bash)
