name: CI
on: [push, pull_request]

jobs:
  test:
    name: Dub Test
    strategy:
      matrix:
        dc:
          - dmd-2.103.1
          - dmd-2.100.0
          - ldc-1.32.2
          - ldc-1.29.0

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1.3.0
        with:
          compiler: ${{ matrix.dc }}

      - name: Test
        run: dub test -q --build=unittest-cov

      - name: Build binary
        run: dub build -q

      - uses: codecov/codecov-action@v3.1.4
